/**************************************************************************************************
 * Filename:       Interface_srpcserver.h
 * Author:             zxb
 * E-Mail:          zxb@yystart.com
 * Description:    Socket Remote Procedure Call Interface - sample device application.
 *
 *  Copyright (C) 2014 Yun Yin Company - http://www.yystart.com/
 *
 * Version:
 *
 */

#ifndef _SRPCSERVER_DEFS_H_
#define _SRPCSERVER_DEFS_H_

#ifdef __cplusplus
extern "C" {
#endif

//包头起始标志
#define CMD_MSG_FLAG    		0xFC

#define CMD_MSG_TP        		USRTP

#define CMD_MSG_DIR_REQ         0x01
#define CMD_MSG_DIR_CFM         0x02
#define CMD_MSG_DIR_IND         0x03
#define CMD_MSG_DIR_RESP        0x04

//数据包部分位置标志
#define CMD_MSG_FLAG_POS    0
#define CMD_MSG_LEN0_POS    1
#define CMD_MSG_LEN1_POS    2
#define CMD_MSG_TP_POS    	3

//opcode D0定义
#define WIFI_SYSMTEM_PROCESS_ID							0x0000
#define WIFI_DEVICE_MANAGER_ID							0x0100

#define WIFI_PERMISSION_ID								0X0200


#define WIFI_TIMER_MANAGER_ID							0x0300
#define WIFI_GROUP_SCENE_ID								0x0400
#define WIFI_ACTION_EVENT_ID							0x0500

#define WIFI_SWITCH_DEVICE_ID							0x1000
#define WIFI_CURTAIN_DEVICE_ID							0x1100
#define WIFI_INFRARED_DEVICE_ID							0x1200
#define WIFI_HUMITURE_DEVICE_ID							0x2000
#define WIFI_HUMITURE_CTL_DEVICE_ID						0x2900
#define WIFI_ENVIRONMENT_DEVICE_ID						0x2200

#define WIFI_COORD_DEVICE_ID							0x2700

#define WIFI_ALARM_DEVICE_ID							0x3000
#define WIFI_DOORLOCk_DEVICE_ID							0x4000
#define WIFI_POWERSWITCH_DEVICE_ID						0x4100
#define WIFI_CENTRALAIR_DEVICE_ID						0x4200


/********************************数据包的Opcode 定义**************************************/
//                                                                          		D0D1

#define WIFI_CONFIG_SSID_PASSWD_CMD_REQ             	0x0001
#define WIFI_CONFIG_SSID_PASSWD_CMD_CFM             	WIFI_CONFIG_SSID_PASSWD_CMD_REQ

#define WIFI_CONFIG_LAN_ETHERNET_CMD_REQ             	0x0002
#define WIFI_CONFIG_LAN_ETHERNET_CMD_CFM             	WIFI_CONFIG_LAN_ETHERNET_CMD_REQ

#define WIFI_GET_MAC_ADDR_CMD_REQ                       0x0003
#define WIFI_GET_MAC_ADDR_CMD_CFM                       WIFI_GET_MAC_ADDR_CMD_REQ

#define WIFI_GET_COORD_VERSION_CMD_REQ                  0x0004
#define WIFI_GET_COORD_VERSION_CMD_CFM                  WIFI_GET_COORD_VERSION_CMD_REQ

#define WIFI_CONFIG_AP_SSID_CMD_REQ             		0x0005
#define WIFI_CONFIG_AP_SSID_CMD_CFM             		WIFI_CONFIG_AP_SSID_CMD_REQ

#define WIFI_CONFIG_GET_VERSION_CMD_REQ             	0x0006
#define WIFI_CONFIG_GET_VERSION_CMD_CFM             	WIFI_CONFIG_GET_VERSION_CMD_REQ


#define WIFI_MODIFY_SSID_REQ							0x0007
#define WIFI_MODIFY_SSID_CFM							WIFI_MODIFY_SSID_REQ

#define WIFI_MODIFY_PASSWORD_REQ						0x0008
#define WIFI_MODIFY_PASSWORD_CFM						WIFI_MODIFY_PASSWORD_REQ

#define WIFI_SYSTEM_REBOOT_REQ							0x0009
#define WIFI_SYSTEM_REBOOT_CFM							WIFI_SYSTEM_REBOOT_REQ

#define WIFI_OPEN_NETWORK_CMD_REQ             			0x0010
#define WIFI_OPEN_NETWORK_CMD_CFM             			WIFI_OPEN_NETWORK_CMD_REQ

#define WIFI_CLOSE_NETWORK_CMD_REQ             			0x0011
#define WIFI_CLOSE_NETWORK_CMD_CFM          			WIFI_CLOSE_NETWORK_CMD_REQ


#define WIFI_REVERT_ALL_DEV_FACTORY_SETTING_CMD_REQ     0x0012
#define WIFI_REVERT_ALL_DEV_FACTORY_SETTING_CMD_CFM     WIFI_REVERT_ALL_DEV_FACTORY_SETTING_CMD_REQ

#define WIFI_REVERT_ONE_DEV_FACTORY_SETTING_CMD_REQ     0x0013
#define WIFI_REVERT_ONE_DEV_FACTORY_SETTING_CMD_CFM     WIFI_REVERT_ONE_DEV_FACTORY_SETTING_CMD_REQ

#define WIFI_GET_COORD_VERSION_CMD_IND     				0x0014
#define WIFI_GET_COORD_VERSION_CMD_RESP     			WIFI_GET_COORD_VERSION_CMD_IND

#define WIFI_SET_COORD_RESET_REQ						0x0015
#define WIFI_SET_COORD_RESET_CFM						WIFI_SET_COORD_RESET_REQ
#define WIFI_SET_COORD_RESET_IND						WIFI_SET_COORD_RESET_REQ



#define WIFI_SET_MASTER_HOST_UPDATE_REQ    				0x0016
#define WIFI_SET_MASTER_HOST_UPDATE_CFM     			WIFI_SET_MASTER_HOST_UPDATE_REQ

#define WIFI_SET_COORD_CHANNELS_REQ						0x0017
#define WIFI_SET_COORD_CHANNELS_CFM						WIFI_SET_COORD_CHANNELS_REQ

#define WIFI_GET_PANID_AND_CHANNELS_REQ					0x0018
#define WIFI_SET_COORD_CHANNELS_IND						WIFI_GET_PANID_AND_CHANNELS_REQ

#define WIFI_GATEWAY_FACTORY_IND						0X00FF
#define WIFI_GATEWAY_FACTORY_RESP						WIFI_GATEWAY_FACTORY_IND		

/**********************************所有产品管理**********************************************/
#define WIFI_ROOMFAIRY_REGISTER_IND             		0x0101
#define WIFI_ROOMFAIRY_REGISTER_RESP           			WIFI_ROOMFAIRY_REGISTER_IND

#define WIFI_ONLINE_DEVICE_HEART_IND           			0x0102 //设备在线的心跳报上报
#define WIFI_ONLINE_DEVICE_HEART_RESP          			WIFI_ONLINE_DEVICE_HEART_IND

#define WIFI_ALLOW_DEV_CONN_NET_REQ           			0x0103    //允许设备入网的命令
#define WIFI_ALLOW_DEV_CONN_NET_CFM           			WIFI_ALLOW_DEV_CONN_NET_REQ

#define WIFI_QUERY_ALL_UNREGISTER_DEV_REQ           	0x0104    //查询所有未注册的节点
#define WIFI_QUERY_ALL_UNREGISTER_DEV_CFM           	WIFI_QUERY_ALL_UNREGISTER_DEV_REQ

#define WIFI_DELETE_DEV_CONN_NET_REQ           			0x0105    //删除已经入网的设备命令
#define WIFI_DELETE_DEV_CONN_NET_CFM           			WIFI_DELETE_DEV_CONN_NET_REQ


#define WIFI_QUERY_ONLINE_DEVICE_REQ           			0x0106    //删除已经入网的设备命令
#define WIFI_QUERY_ONLINE_DEVICE_CFM           			WIFI_QUERY_ONLINE_DEVICE_REQ


#define WIFI_HOST_PERMISSION_IND						0x0200
#define WIFI_HOST_PERMISSION_RESP						WIFI_HOST_PERMISSION_IND

//Zigbee开关节点注册
#define WIFI_ZIGBEE_COM_DEV_REGISTER_IND          		0x0110
#define WIFI_ZIGBEE_COM_DEV_REGISTER_RESP        		WIFI_ZIGBEE_COM_DEV_REGISTER_IND

#define WIFI_ZIGBEE_GET_VERSION_REQ          			0x0111
#define WIFI_ZIGBEE_GET_VERSION_CFM       				WIFI_ZIGBEE_GET_VERSION_REQ

#define WIFI_ZIGBEE_GET_VERSION_IND       				0X0112
#define WIFI_ZIGBEE_GET_VERSION_RESP       				WIFI_ZIGBEE_GET_VERSION_IND
/**********************************协调器控制管理********************************************/
#define ZIGBEE_DEVICE_UTIL_GET_DEVICE_INFO_REQ			0x2700
#define ZIGBEE_DEVICE_UTIL_GET_DEVICE_INFO_CFM			ZIGBEE_DEVICE_UTIL_GET_DEVICE_INFO_REQ


#define ZIGBEE_DEVICE_MT_NETWORK_CONFLICT_IND			0x6554
#define ZIGBEE_DEVICE_MT_NETWORK_CONFLICT_RESP			ZIGBEE_DEVICE_MT_NETWORK_CONFLICT_IND

#define ZIGBEE_DEVICE_MT_SERIAL_STATE_IND				0x6555
#define ZIGBEE_DEVICE_MT_SERIAL_STATE_RESP				ZIGBEE_DEVICE_MT_SERIAL_STATE_IND


/**********************************卧室精灵控制**********************************************/
#define WIFI_ROOMFAIRY_LIGHT_CTRL_REQ          			0x0201
#define WIFI_ROOMFAIRY_LIGHT_CTRL_CFM        			WIFI_ROOMFAIRY_LIGHT_CTRL_REQ

#define WIFI_ROOMFAIRY_LIGHT_STATUS_IND          		0x0202
#define WIFI_ROOMFAIRY_LIGHT_STATUS_RESP       	 		WIFI_ROOMFAIRY_LIGHT_STATUS_IND

#define WIFI_ROOMFAIRY_ADD_CLOCK_REQ          			0x0211
#define WIFI_ROOMFAIRY_ADD_CLOCK_CFM        			WIFI_ROOMFAIRY_ADD_CLOCK_REQ

#define WIFI_ROOMFAIRY_DELETE_CLOCK_REQ          		0x0212
#define WIFI_ROOMFAIRY_DELETE_CLOCK_CFM        			WIFI_ROOMFAIRY_DELETE_CLOCK_REQ


/********************************** 节点定时控制**********************************************/
#define WIFI_ZIGBEE_PERIOD_TIMER_SWITCH_SET_REQ         0x0301
#define WIFI_ZIGBEE_PERIOD_TIMER_SWITCH_SET_CFM        	WIFI_ZIGBEE_PERIOD_TIMER_SWITCH_SET_REQ

#define WIFI_ZIGBEE_DELETE_PERIOD_TIMER_SWITCH_REQ      0x0302
#define WIFI_ZIGBEE_DELETE_PERIOD_TIMER_SWITCH_CFM      WIFI_ZIGBEE_DELETE_PERIOD_TIMER_SWITCH_REQ

#define WIFI_ZIGBEE_GET_PERIOD_TIMER_SWITCH_REQ      	0x0303
#define WIFI_ZIGBEE_GET_PERIOD_TIMER_SWITCH_CFM      	WIFI_ZIGBEE_GET_PERIOD_TIMER_SWITCH_REQ

#define WIFI_ZIGBEE_CTL_PERIOD_TIMER_SWITCH_REQ      	0x0304
#define WIFI_ZIGBEE_CTL_PERIOD_TIMER_SWITCH_CFM      	WIFI_ZIGBEE_CTL_PERIOD_TIMER_SWITCH_REQ

#define WIFI_ZIGBEE_PERIOD_TIMER_SWITCH_INFO_IND      	0x0305
#define WIFI_ZIGBEE_PERIOD_TIMER_SWITCH_INFO_RESP      	WIFI_ZIGBEE_PERIOD_TIMER_SWITCH_INFO_IND


/********************************** 组管理及场景管理**********************************************/
#define WIFI_ZIGBEE_ADD_DEV_GROUP_REQ          			0x0401
#define WIFI_ZIGBEE_ADD_DEV_GROUP_CFM        			WIFI_ZIGBEE_ADD_DEV_GROUP_REQ
#define WIFI_ZIGBEE_ADD_DEV_GROUP_RESP        			WIFI_ZIGBEE_ADD_DEV_GROUP_REQ

#define WIFI_ZIGBEE_DEL_DEV_GROUP_REQ          			0x0402
#define WIFI_ZIGBEE_DEL_DEV_GROUP_CFM        			WIFI_ZIGBEE_DEL_DEV_GROUP_REQ

#define WIFI_ZIGBEE_GET_DEV_GROUP_REQ          			0x0403
#define WIFI_ZIGBEE_GET_DEV_GROUP_CFM        			WIFI_ZIGBEE_GET_DEV_GROUP_REQ

#define WIFI_ZIGBEE_CTL_DEV_GROUP_REQ          			0x0404
#define WIFI_ZIGBEE_CTL_DEV_GROUP_CFM        			WIFI_ZIGBEE_CTL_DEV_GROUP_REQ

#define WIFI_ZIGBEE_DEV_GROUP_IND						0x0405
#define WIFI_ZIGBEE_DEV_GROUP_RESP						WIFI_ZIGBEE_DEV_GROUP_IND

/**********************************开关节点控制**********************************************/
#define WIFI_ZIGBEE_SWITCH_CTRL_REQ          			0x1001
#define WIFI_ZIGBEE_SWITCH_CTRL_CFM        				WIFI_ZIGBEE_SWITCH_CTRL_REQ

#define WIFI_ZIGBEE_SWITCH_STATUS_IND          			0x1002
#define WIFI_ZIGBEE_SWITCH_STATUS_RESP        			WIFI_ZIGBEE_SWITCH_STATUS_IND

#define WIFI_ZIGBEE_QUERY_SWITCH_STATUS_REQ          	0x1003
#define WIFI_ZIGBEE_QUERY_SWITCH_STATUS_CFM        		WIFI_ZIGBEE_QUERY_SWITCH_STATUS_REQ

#define WIFI_ZIGBEE_QUERY_ALL_SWITCH_STATUS_REQ         0x1004
#define WIFI_ZIGBEE_QUERY_ALL_SWITCH_STATUS_CFM        	WIFI_ZIGBEE_QUERY_ALL_SWITCH_STATUS_REQ

#define WIFI_ZIGBEE_SET_SWITCH_DEFAULT_REQ				0x1005
#define WIFI_ZIGBEE_SET_SWITCH_DEFAULT_CFM				WIFI_ZIGBEE_SET_SWITCH_DEFAULT_REQ

#define WIFI_ZIGBEE_GET_SWITCH_DEFAULT_REQ				0x1006
#define WIFI_ZIGBEE_GET_SWITCH_DEFAULT_CFM				WIFI_ZIGBEE_GET_SWITCH_DEFAULT_REQ	

#define WIFI_ZIGBEE_SWITCH_DEFAULT_IND					0x1007
#define WIFI_ZIGBEE_SWITCH_DEFAULT_RESP					WIFI_ZIGBEE_SWITCH_DEFAULT_IND	

#define WIFI_ZIGBEE_QUERY_SIWTCH_VALUE_REQ				0x1010
#define WIFI_ZIGBEE_QUERY_SIWTCH_VALUE_CFM				WIFI_ZIGBEE_QUERY_SIWTCH_VALUE_REQ

#define WIFI_ZIGBEE_QUERY_SIWTCH_VALUE_IND				0x1011
#define WIFI_ZIGBEE_QUERY_SIWTCH_VALUE_RESP				WIFI_ZIGBEE_QUERY_SIWTCH_VALUE_IND


/**********************************窗帘控制器节点控制**********************************************/
#define WIFI_ZIGBEE_WIN_CURTAIN_CTRL_REQ          		0x1101
#define WIFI_ZIGBEE_WIN_CURTAIN_CTRL_CFM        		WIFI_ZIGBEE_WIN_CURTAIN_CTRL_REQ

#define WIFI_ZIGBEE_WIN_CURTAIN_STATUS_IND				0x1102
#define WIFI_ZIGBEE_WIN_CURTAIN_STATUS_RESP				WIFI_ZIGBEE_WIN_CURTAIN_STATUS_IND

#define WIFI_ZIGBEE_WIN_CURTAIN_PERCENTAGE_REQ			0x1103
#define WIFI_ZIGBEE_WIN_CURTAIN_PERCENTAGE_CFM			WIFI_ZIGBEE_WIN_CURTAIN_PERCENTAGE_REQ

#define WIFI_ZIGBEE_WIN_CURTAIN_PERCENTAGE_IND			0x1104
#define WIFI_ZIGBEE_WIN_CURTAIN_PERCENTAGE_RESP			WIFI_ZIGBEE_WIN_CURTAIN_PERCENTAGE_IND

/**********************************红外转发器节点控制**********************************************/
#define WIFI_ZIGBEE_IRC_ENTER_LEARN_REQ          		0x1201
#define WIFI_ZIGBEE_IRC_ENTER_LEARN_CFM        			WIFI_ZIGBEE_IRC_ENTER_LEARN_REQ

#define WIFI_ZIGBEE_IRC_EXIT_LEARN_REQ          		0x1202
#define WIFI_ZIGBEE_IRC_EXIT_LEARN_CFM        			WIFI_ZIGBEE_IRC_EXIT_LEARN_REQ

#define WIFI_ZIGBEE_IRC_SET_LEARN_ADDR_REQ          	0x1203
#define WIFI_ZIGBEE_IRC_SET_LEARN_ADDR_CFM        		WIFI_ZIGBEE_IRC_SET_LEARN_ADDR_REQ

#define WIFI_ZIGBEE_IRC_LEARN_STATUS_IND          		0x1204
#define WIFI_ZIGBEE_IRC_LEARN_STATUS_RESP        		WIFI_ZIGBEE_IRC_LEARN_STATUS_IND

#define WIFI_ZIGBEE_IRC_SEND_CTRL_REQ          			0x1210
#define WIFI_ZIGBEE_IRC_SEND_CTRL_CFM        			WIFI_ZIGBEE_IRC_SEND_CTRL_REQ

#define WIFI_ZIGBEE_REMOTE_IRC_ENTER_LEARN_REQ          0x1211
#define WIFI_ZIGBEE_REMOTE_IRC_ENTER_LEARN_CFM        	WIFI_ZIGBEE_REMOTE_IRC_ENTER_LEARN_REQ

#define WIFI_ZIGBEE_REMOTE_IRC_EXIT_LEARN_REQ          	0x1212
#define WIFI_ZIGBEE_REMOTE_IRC_EXIT_LEARN_CFM        	WIFI_ZIGBEE_REMOTE_IRC_EXIT_LEARN_REQ

#define WIFI_ZIGBEE_REMOTE_IRC_SEND_CTRL_REQ          	0x1214
#define WIFI_ZIGBEE_REMOTE_IRC_SEND_CTRL_CFM        	WIFI_ZIGBEE_REMOTE_IRC_SEND_CTRL_REQ

#define WIFI_ZIGBEE_REMOTE_IRC_DEVICE_CFM				0x1219

#define WIFI_ZIGBEE_REMOTE_IRC_QUERY_DEVICE_REQ         0x1220
#define WIFI_ZIGBEE_REMOTE_IRC_QUERY_DEVICE_CFM        	WIFI_ZIGBEE_REMOTE_IRC_QUERY_DEVICE_REQ

#define WIFI_ZIGBEE_REMOTE_IRC_CTL_DEVICE_REQ         	0x1221
#define WIFI_ZIGBEE_REMOTE_IRC_CTL_DEVICE_CFM        	WIFI_ZIGBEE_REMOTE_IRC_CTL_DEVICE_REQ

#define WIFI_ZIGBEE_REMOTE_IRC_QUERY_DEVICE_ID_REQ         	0x1222
#define WIFI_ZIGBEE_REMOTE_IRC_QUERY_DEVICE_ID_CFM        	WIFI_ZIGBEE_REMOTE_IRC_QUERY_DEVICE_ID_REQ


#define WIFI_ZIGBEE_REMOTE_IRC_ENTER_LEARN_MODE_REQ     0x1223
#define WIFI_ZIGBEE_REMOTE_IRC_ENTER_LEARN_MODE_CFM     WIFI_ZIGBEE_REMOTE_IRC_ENTER_LEARN_MODE_REQ

//#define WIFI_ZIGBEE_REMOTE_IRC_EXIT_LEARN_MODE_REQ      0x1224
//#define WIFI_ZIGBEE_REMOTE_IRC_EXIT_LEARN_MODE_CFM      WIFI_ZIGBEE_REMOTE_IRC_EXIT_LEARN_MODE_REQ

#define WIFI_ZIGBEE_REMOTE_IRC_LEARN_DATA_IND			0x1224
#define WIFI_ZIGBEE_REMOTE_IRC_LEARN_DATA_RESP			WIFI_ZIGBEE_REMOTE_IRC_LEARN_DATA_IND

#define WIFI_ZIGBEE_REMOTE_IRC_SEND_RAW_DATA_REQ		0x1225
#define WIFI_ZIGBEE_REMOTE_IRC_SEND_RAW_DATA_CMF		WIFI_ZIGBEE_REMOTE_IRC_SEND_RAW_DATA_REQ

#define WIFI_ZIGBEE_REMOTE_IRC_CODE_LIB_IND				0x1226
#define WIFI_ZIGBEE_REMOTE_IRC_CODE_LIB_RESP			WIFI_ZIGBEE_REMOTE_IRC_CODE_LIB_IND


#define WIFI_ZIGBEE_REMOTE_IRC_EXIT_LEARN_MODE_REQ_TEST      0x1230

/**********************************温湿度光照节点控制**********************************************/
//#define WIFI_ZIGBEE_HUMITURE_LIGHT_CTRL_REQ          	0x2001
//#define WIFI_ZIGBEE_HUMITURE_LIGHT_CTRL_CFM        		WIFI_ZIGBEE_HUMITURE_LIGHT_CTRL_REQ

//#define WIFI_ZIGBEE_HUMITURE_LIGHT_STATUS_IND          	0x2002
//#define WIFI_ZIGBEE_HUMITURE_LIGHT_STATUS_RESP        	WIFI_ZIGBEE_HUMITURE_LIGHT_STATUS_IND

//#define WIFI_ZIGBEE_QUERY_HUMITURE_LIGHT_STATUS_REQ     0x2003
//#define WIFI_ZIGBEE_QUERY_HUMITURE_LIGHT_STATUS_CFM     WIFI_ZIGBEE_QUERY_HUMITURE_LIGHT_STATUS_REQ

/**********************************温湿度节点控制**********************************************/
#define WIFI_ZIGBEE_HUMITURE_CTRL_REQ          			0x2901
#define WIFI_ZIGBEE_HUMITURE_CTRL_CFM        			WIFI_ZIGBEE_HUMITURE_CTRL_REQ

#define WIFI_ZIGBEE_HUMITURE_STATUS_IND          		0x2902
#define WIFI_ZIGBEE_HUMITURE_STATUS_RESP        		WIFI_ZIGBEE_HUMITURE_STATUS_IND

#define WIFI_ZIGBEE_QUERY_HUMITURE_STATUS_REQ          	0x2903
#define WIFI_ZIGBEE_QUERY_HUMITURE_STATUS_CFM        	WIFI_ZIGBEE_QUERY_HUMITURE_STATUS_REQ

#define WIFI_ZIGBEE_HUMITURE_ENABLE_REQ          		0x2904
#define WIFI_ZIGBEE_HUMITURE_ENBALE_CFM        			WIFI_ZIGBEE_HUMITURE_ENABLE_REQ

/**********************************环境检测器节点控制**********************************************/

#define WIFI_ZIGBEE_ENVIRONMENT_LIGHT_STATUS_IND         0x2201
#define WIFI_ZIGBEE_ENVIRONMENT_LIGHT_STATUS_RESP        WIFI_ZIGBEE_ENVIRONMENT_LIGHT_STATUS_IND

#define WIFI_ZIGBEE_ENVIRONMENT_TEMPHUM_STATUS_IND       0x2202
#define WIFI_ZIGBEE_ENVIRONMENT_TEMPHUM_STATUS_RESP      WIFI_ZIGBEE_ENVIRONMENT_TEMPHUM_STATUS_IND

#define WIFI_ZIGBEE_ENVIRONMENT_PM25_STATUS_IND          0x2203
#define WIFI_ZIGBEE_ENVIRONMENT_PM25_STATUS_RESP         WIFI_ZIGBEE_ENVIRONMENT_PM25_STATUS_IND

#define WIFI_ZIGBEE_ENVIRONMENT_NOICE_STATUS_IND         0x2204
#define WIFI_ZIGBEE_ENVIRONMENT_NOICE_STATUS_RESP        WIFI_ZIGBEE_ENVIRONMENT_NOICE_STATUS_IND

/**********************************报警器节点控制**********************************************/
#define WIFI_ZIGBEE_COM_ALARM_CTRL_REQ          		0x3001
#define WIFI_ZIGBEE_COM_ALARM_CTRL_CFM        			WIFI_ZIGBEE_COM_ALARM_CTRL_REQ

#define WIFI_ZIGBEE_COM_ALARM_STATUS_IND          		0x3002
#define WIFI_ZIGBEE_COM_ALARM_STATUS_RESP        		WIFI_ZIGBEE_COM_ALARM_STATUS_IND

#define WIFI_ZIGBEE_COM_ALARM_POWER_VALUE_IND          	0x3003
#define WIFI_ZIGBEE_COM_ALARM_POWER_VALUE_RESP        	WIFI_ZIGBEE_COM_ALARM_POWER_VALUE_IND

#define WIFI_ZIGBEE_COM_ALARM_ENABLE_IND          		0x3004
#define WIFI_ZIGBEE_COM_ALARM_ENABLE_RESP        		WIFI_ZIGBEE_COM_ALARM_ENABLE_IND

#define WIFI_ZIGBEE_COM_ALARM_GET_POWERS_REQ			0x3005
#define WIFI_ZIGBEE_COM_ALARM_GET_POWERS_CFM			WIFI_ZIGBEE_COM_ALARM_GET_POWERS_REQ

/**********************************门锁节点控制**********************************************/
#define WIFI_ZIGBEE_DOORLOCK_CTRL_REQ        			0x4001
#define WIFI_ZIGBEE_DOORLOCK_CTRL_CFM        			WIFI_ZIGBEE_DOORLOCK_CTRL_REQ

#define WIFI_ZIGBEE_DOORLOCK_STATUS_IND          		0x4002
#define WIFI_ZIGBEE_DOORLOCK_STATUS_RESP        		WIFI_ZIGBEE_DOORLOCK_STATUS_IND

#define WIFI_ZIGBEE_DOORLOCK_POWER_VALUE_IND          	0x4003
#define WIFI_ZIGBEE_DOORLOCK_POWER_VALUE_RESP        	WIFI_ZIGBEE_DOORLOCK_POWER_VALUE_IND

#define WIFI_ZIGBEE_QUERY_DOORLOCK_POWER_VALUE_REQ      0x4004
#define WIFI_ZIGBEE_QUERY_DOORLOCK_POWER_VALUE_CFM      WIFI_ZIGBEE_QUERY_DOORLOCK_POWER_VALUE_REQ
#define WIFI_ZIGBEE_QUERY_DOORLOCK_POWER_VALUE_RESP     WIFI_ZIGBEE_QUERY_DOORLOCK_POWER_VALUE_REQ

#define WIFI_ZIGBEE_QUERY_DOORLOCK_SPEED_REQ      		0x4006
#define WIFI_ZIGBEE_QUERY_DOORLOCK_SPEED_CFM      		WIFI_ZIGBEE_QUERY_DOORLOCK_SPEED_REQ

#define WIFI_ZIGBEE_SET_DOORLOCK_SPEED_REQ      		0x4007
#define WIFI_ZIGBEE_SET_DOORLOCK_SPEED_CFM      		WIFI_ZIGBEE_SET_DOORLOCK_SPEED_REQ


////////////////LEVEL门锁

#define WIFI_ZIGBEE_GET_LEVEL_DOOR_INFO_REQ				0x4010
#define WIFI_ZIGBEE_GET_LEVEL_DOOR_INFO_CFM				WIFI_ZIGBEE_GET_LEVEL_DOOR_INFO_REQ

#define WIFI_ZIGBEE_LEVEL_DOOR_INFO_IND					0x4011
#define WIFI_ZIGBEE_LEVEL_DOOR_INFO_RESP				WIFI_ZIGBEE_LEVEL_DOOR_INFO_IND

#define WIFI_ZIGBEE_LEVEL_DOOR_POWER_IND				0x4012
#define WIFI_ZIGBEE_LEVEL_DOOR_POWER_RESP				WIFI_ZIGBEE_LEVEL_DOOR_POWER_IND

#define WIFI_ZIGBEE_LEVEL_DOOR_RECORD_IND				0x4013
#define WIFI_ZIGBEE_LEVEL_DOOR_RECORD_RESP				WIFI_ZIGBEE_LEVEL_DOOR_RECORD_IND

#define WIFI_ZIGBEE_LEVEL_DOOR_ALARMOPT_IND				0x4014
#define WIFI_ZIGBEE_LEVEL_DOOR_ALARMOPT_RESP			WIFI_ZIGBEE_LEVEL_DOOR_ALARMOPT_IND

#define WIFI_ZIGBEE_SET_LEVEL_DOOR_TIME_REQ				0x4015
#define WIFI_ZIGBEE_SET_LEVEL_DOOR_TIME_CFM				WIFI_ZIGBEE_SET_LEVEL_DOOR_TIME_REQ

#define WIFI_ZIGBEE_GET_LEVEL_DOOR_REG_REQ				0x4016
#define WIFI_ZIGBEE_GET_LEVEL_DOOR_REG_CFM				WIFI_ZIGBEE_GET_LEVEL_DOOR_REG_REQ

#define WIFI_ZIGBEE_GET_LEVEL_DOOR_REG_IND				0x4017
#define WIFI_ZIGBEE_GET_LEVEL_DOOR_REG_RESP				WIFI_ZIGBEE_GET_LEVEL_DOOR_REG_IND

#define WIFI_ZIGBEE_ADD_LEVEL_DOOR_USR_REQ				0x4018
#define WIFI_ZIGBEE_ADD_LEVEL_DOOR_USR_CFM				WIFI_ZIGBEE_ADD_LEVEL_DOOR_USR_REQ

#define WIFI_ZIGBEE_ADD_LEVEL_DOOR_USR_IND				0x4019
#define WIFI_ZIGBEE_ADD_LEVEL_DOOR_USR_RESP				WIFI_ZIGBEE_ADD_LEVEL_DOOR_USR_IND

#if DEVICE_LIWEI_DOOR_OPEN_CNT
#define WIFI_ZIGBEE_GET_LEVEL_DOOR_OPEN_CNT_REQ			0x4000
#define WIFI_ZIGBEE_GET_LEVEL_DOOR_OPEN_CNT_CFM         WIFI_ZIGBEE_GET_LEVEL_DOOR_OPEN_CNT_REQ
#define WIFI_ZIGBEE_GET_LEVEL_DOOR_OPEN_CNT_IND         WIFI_ZIGBEE_GET_LEVEL_DOOR_OPEN_CNT_REQ
#define WIFI_ZIGBEE_GET_LEVEL_DOOR_OPEN_CNT_RESP        WIFI_ZIGBEE_GET_LEVEL_DOOR_OPEN_CNT_REQ
#endif
/**********************************取电节点控制**********************************************/
#define WIFI_ZIGBEE_POWERSWITCH_CTRL_REQ        		0x4101
#define WIFI_ZIGBEE_POWERSWITCH_CTRL_CFM        		WIFI_ZIGBEE_POWERSWITCH_CTRL_REQ

#define WIFI_ZIGBEE_POWERSWITCH_STATUS_IND          	0x4102
#define WIFI_ZIGBEE_POWERSWITCH_STATUS_RESP        		WIFI_ZIGBEE_POWERSWITCH_STATUS_IND

#define WIFI_ZIGBEE_POWERSWITCH_POWER_VALUE_IND         0x4103
#define WIFI_ZIGBEE_POWERSWITCH_POWER_VALUE_RESP        WIFI_ZIGBEE_POWERSWITCH_POWER_VALUE_IND

#define WIFI_ZIGBEE_QUERY_POWERSWITCH_POWER_VALUE_REQ   0x4104
#define WIFI_ZIGBEE_QUERY_POWERSWITCH_POWER_VALUE_RESP  WIFI_ZIGBEE_QUERY_POWERSWITCH_POWER_VALUE_REQ
#define WIFI_ZIGBEE_QUERY_POWERSWITCH_POWER_VALUE_CFM  WIFI_ZIGBEE_QUERY_POWERSWITCH_POWER_VALUE_REQ

#define WIFI_ZIGBEE_QUERY_POWERSWITCH_STATUS_REQ   		0x4105
#define WIFI_ZIGBEE_QUERY_POWERSWITCH_STATUS_RESP 		WIFI_ZIGBEE_QUERY_POWERSWITCH_STATUS_REQ
#define WIFI_ZIGBEE_QUERY_POWERSWITCH_STATUS_CFM 		WIFI_ZIGBEE_QUERY_POWERSWITCH_STATUS_REQ

/***********************************中央空调控制器***********************************************/

#define WIFI_ZIGBEE_SET_CENTRAL_AIR_REQ					0x4201
#define WIFI_ZIGBEE_SET_CENTRAL_AIR_CFM					WIFI_ZIGBEE_SET_CENTRAL_AIR_REQ

#define WIFI_ZIGBEE_CENTRAL_AIR_STATE_IND				0x4202
#define WIFI_ZIGBEE_CENTRAL_AIR_STATE_RESP				WIFI_ZIGBEE_CENTRAL_AIR_STATE_IND

#define WIFI_ZIGBEE_QUERY_CENTRAL_AIR_REQ				0x4203
#define WIFI_ZIGBEE_QUERY_CENTRAL_AIR_CFM				WIFI_ZIGBEE_QUERY_CENTRAL_AIR_REQ


/**********************************事件管理**********************************************/

#define WIFI_ZIGBEE_ACTION_EVENT_ADD_REQ				0x0501
#define WIFI_ZIGBEE_ACTION_EVENT_ADD_CFM				WIFI_ZIGBEE_ACTION_EVENT_ADD_REQ

#define WIFI_ZIGBEE_ACTION_EVENT_DEL_REQ				0x0502
#define WIFI_ZIGBEE_ACTION_EVENT_DEL_CFM				WIFI_ZIGBEE_ACTION_EVENT_DEL_REQ

#define WIFI_ZIGBEE_ACTION_EVENT_GET_REQ				0x0503
#define WIFI_ZIGBEE_ACTION_EVENT_GET_CFM				WIFI_ZIGBEE_ACTION_EVENT_GET_REQ

#define WIFI_ZIGBEE_ACTION_EVENT_CTL_REQ				0x0504
#define WIFI_ZIGBEE_ACTION_EVENT_CTL_CFM				WIFI_ZIGBEE_ACTION_EVENT_CTL_REQ

#define WIFI_ZIGBEE_ACTION_EVENT_STATE_IND				0x0505
#define WIFI_ZIGBEE_ACTION_EVENT_STATE_RESP				WIFI_ZIGBEE_ACTION_EVENT_STATE_IND


#ifdef __cplusplus
}
#endif

#endif //COM_MSG_PRIVATE_H
