TOPDIR=../..

INCLUDE_DIR=..

include $(TOPDIR)/include.mk
#INCLUDE = -I../../lib/libapr-1/include/apr-1/ -I../../lib/libaprutil-1/include/apr-1/  -I../../lib/libcurl/include  -I../../lib/libmxml/include/ -L../../lib/libmxml/lib/ 
CFLAGS += $(INCLUDE)		

include $(TOPDIR)/config.mk
